In [1]:
import numpy as np

In [2]:
a= np.array([[[1,2,3],[4,5,6],[1,5,5]]])

In [3]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 5, 5]]])

In [4]:
a.shape

(1, 3, 3)

In [18]:
b=np.array([[[1,2,3],[4,5,6],[1,5,5]],[[4,5,6]]])

In [19]:
b.shape

(2,)

In [20]:
b.ndim

1

In [21]:
b

array([list([[1, 2, 3], [4, 5, 6], [1, 5, 5]]), list([[4, 5, 6]])],
      dtype=object)

In [22]:
q= np.array([[1,2,3],[45,78,90]])

In [23]:
q

array([[ 1,  2,  3],
       [45, 78, 90]])

In [24]:
#slice and take out 45

In [28]:
a[1][0]

45

In [29]:
a[1:0]

array([], shape=(0, 3, 3), dtype=int32)

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
#arange function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])