In [2]:
# 3*3 matrix zeroes it is a 2d 
import numpy as np
a= np.zeros([3,3])

In [4]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b= np.zeros([3,3,3]) 
# as the element will increase dimension 
#will increase


In [9]:
b.ndim

3

In [10]:
# for 1d
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones([3])

array([1., 1., 1.])

In [12]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
x= np.ones([3,5,2])
# 5 rows, 2 column and 3 layers 

In [15]:
x.ndim

3

In [16]:
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [25]:
a= [1,2,3]
b= [4,5,6]
c=[]
for i in range(0,len(a)):
        res = a[i]+ b[i]
        c.append(res)
print(c)

[5, 7, 9]


In [31]:
y= np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
y.sum(axis=0)

array([5, 7, 9])

In [33]:
y.sum(axis=1)

array([ 6, 15])

In [35]:
x= np.array([[[1,2,4],[4,5,6],[2,2,2]]])

In [36]:
x.sum(axis=0)

array([[1, 2, 4],
       [4, 5, 6],
       [2, 2, 2]])

In [37]:
x.sum(axis=1)

array([[ 7,  9, 12]])

In [38]:
x.sum(axis=2)

array([[ 7, 15,  6]])

In [39]:
x=np.array([[1,2,3],[4,4,5]])

In [40]:
x.ndim

2

In [41]:
x

array([[1, 2, 3],
       [4, 4, 5]])

In [42]:
#tranform
x.T

array([[1, 4],
       [2, 4],
       [3, 5]])

In [3]:
#searching/ sorting
a= np.array([100,34,45,67,77,12,23,90])

In [4]:
a

array([100,  34,  45,  67,  77,  12,  23,  90])

In [45]:
np.where(a%2==0)
#where gives you position of your answer

(array([0, 1, 5, 7], dtype=int64),)

In [5]:
#sorting
a.sort()

In [6]:
a

array([ 12,  23,  34,  45,  67,  77,  90, 100])

In [10]:
np.sort(a, axis=0)

array([ 12,  23,  34,  45,  67,  77,  90, 100])

In [63]:
a= np.array([[100,34,45,67,10],[10,77,12,23,90]])

In [64]:
a

array([[100,  34,  45,  67,  10],
       [ 10,  77,  12,  23,  90]])

In [65]:
a.min()

10

In [66]:
a.max()

100

In [67]:
a.mean()

46.8

In [75]:
#argmax
#argmin
#argsort
x= np.array([[[120,34,23],[990,78,5555],[221,890,6675]]])

In [76]:
x

array([[[ 120,   34,   23],
        [ 990,   78, 5555],
        [ 221,  890, 6675]]])

In [77]:
x.argmax()

8

In [78]:
x.argmin()

2

In [79]:
x.argsort()

array([[[2, 1, 0],
        [1, 0, 2],
        [0, 1, 2]]], dtype=int64)